services:
  db:
    image: mysql:8.0
    restart: always
    environment:
     - MYSQL_DATABASE=book_sharing_db
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=user
     - MYSQL_PASSWORD=userpassword
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password
    networks:
      - book_network

networks:
  book_network:
    driver: bridge

volumes:
  db:
    driver: local